# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8c108b08582dfecb8fa81ec3c0a638242ab6248baa5994901a4358606801cf1cd9d050e79d7219e4d4cb2f8b773903daec77c5a53823537715ade11c67f6bfc

test:
  secret_key_base: fa70ea6f26f9d0d1e26f78867766c5a87d2f4bbacbec2f75e2a2e10e05d230cba4eed7e6e6326df2870c633d517915e85252a680234ff057230a7a8fa7707c22

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
